// <auto-generated />
using System;
using GroupSplit.Data.PostgreSQL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GroupSplit.Data.PostgreSQL.Migrations.Migrations
{
    [DbContext(typeof(PostgreSqlAppDbContext))]
    [Migration("20260909023314_BankRowCategoryIcon")]
    partial class BankRowCategoryIcon
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GroupSplit.Data.Entities.BankConnection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AccessTokenCiphertext")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("AccountsRekeyed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Cursor")
                        .HasColumnType("text");

                    b.Property<string>("InstitutionName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTimeOffset?>("LastSyncedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("LinkedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("ProviderItemId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("Provider", "ProviderItemId")
                        .IsUnique();

                    b.ToTable("BankConnection");
                });

            modelBuilder.Entity("GroupSplit.Data.Entities.BankMatchDismissal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BankTransactionId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("DismissedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("TransactionId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TransactionId");

                    b.HasIndex("BankTransactionId", "TransactionId")
                        .IsUnique();

                    b.ToTable("BankMatchDismissal");
                });

            modelBuilder.Entity("GroupSplit.Data.Entities.BankTransaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateOnly?>("AuthorizedDate")
                        .HasColumnType("date");

                    b.Property<string>("CategoryIconUrl")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("City")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(3)
                        .HasColumnType("character(3)")
                        .HasDefaultValue("USD")
                        .IsFixedLength();

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTimeOffset>("ImportedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("LinkedAccountId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("MerchantId")
                        .HasColumnType("uuid");

                    b.Property<string>("MerchantName")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("PaymentChannel")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<bool>("Pending")
                        .HasColumnType("boolean");

                    b.Property<string>("ProviderCategory")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("ProviderCategoryDetailed")
                        .HasMaxLength(96)
                        .HasColumnType("character varying(96)");

                    b.Property<string>("ProviderTransactionId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("RawJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTimeOffset?>("RemovedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ReplacesId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.HasKey("Id");

                    b.HasIndex("MerchantId");

                    b.HasIndex("ReplacesId");

                    b.HasIndex("LinkedAccountId", "ProviderTransactionId")
                        .IsUnique();

                    b.HasIndex("LinkedAccountId", "Status", "Date");

                    b.ToTable("BankTransaction");
                });

            modelBuilder.Entity("GroupSplit.Data.Entities.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("DefaultSplitRuleId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("GroupId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.HasIndex("DefaultSplitRuleId");

                    b.HasIndex("GroupId", "Name")
                        .IsUnique();

                    b.ToTable("Category");
                });

            modelBuilder.Entity("GroupSplit.Data.Entities.Group", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(3)
                        .HasColumnType("character(3)")
                        .HasDefaultValue("USD")
                        .IsFixedLength();

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.ToTable("Group");
                });

            modelBuilder.Entity("GroupSplit.Data.Entities.GroupInvitation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<Guid>("GroupId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("InvitedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("InvitedByUserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Email");

                    b.HasIndex("InvitedByUserId");

                    b.HasIndex("GroupId", "Email")
                        .IsUnique();

                    b.ToTable("GroupInvitation");
                });

            modelBuilder.Entity("GroupSplit.Data.Entities.GroupJoinLink", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("GroupId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.HasIndex("GroupId", "CreatedAt");

                    b.ToTable("GroupJoinLink");
                });

            modelBuilder.Entity("GroupSplit.Data.Entities.GroupMembership", b =>
                {
                    b.Property<Guid>("GroupId")
                        .HasColumnType("uuid")
                        .HasColumnName("GroupsId");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("UsersId");

                    b.Property<DateTimeOffset?>("ArchivedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("JoinedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("GroupId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("GroupUser", (string)null);
                });

            modelBuilder.Entity("GroupSplit.Data.Entities.LinkedAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BankConnectionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(3)
                        .HasColumnType("character(3)")
                        .HasDefaultValue("USD")
                        .IsFixedLength();

                    b.Property<string>("Mask")
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("ProviderAccountId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Subtype")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("Id");

                    b.HasIndex("BankConnectionId", "ProviderAccountId")
                        .IsUnique();

                    b.ToTable("LinkedAccount");
                });

            modelBuilder.Entity("GroupSplit.Data.Entities.Merchant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("FirstSeenAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LogoUrl")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique();

                    b.ToTable("Merchant");
                });

            modelBuilder.Entity("GroupSplit.Data.Entities.PendingBankLink", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer");

                    b.Property<string>("ItemCiphertext")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("LastAttemptAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("PublicTokenCiphertext")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("Attempts", "StartedAt");

                    b.ToTable("PendingBankLink");
                });

            modelBuilder.Entity("GroupSplit.Data.Entities.SplitRule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("character varying(21)");

                    b.Property<Guid>("GroupId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.HasIndex("Discriminator");

                    b.HasIndex("GroupId", "Name")
                        .IsUnique();

                    b.ToTable("SplitRule");

                    b.HasDiscriminator<string>("Discriminator").HasValue("SplitRule");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("GroupSplit.Data.Entities.SplitRuleParticipant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("SplitRuleId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<int>("Weight")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("SplitRuleId", "UserId")
                        .IsUnique();

                    b.ToTable("SplitRuleParticipant");
                });

            modelBuilder.Entity("GroupSplit.Data.Entities.Transaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<Guid?>("BankTransactionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(3)
                        .HasColumnType("character(3)")
                        .HasDefaultValue("USD")
                        .IsFixedLength();

                    b.Property<DateTimeOffset>("DateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("character varying(13)");

                    b.Property<Guid?>("GroupId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("MerchantId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("BankTransactionId")
                        .IsUnique();

                    b.HasIndex("DateTime");

                    b.HasIndex("Discriminator");

                    b.HasIndex("MerchantId");

                    b.HasIndex("Name");

                    b.HasIndex("UserId");

                    b.HasIndex("GroupId", "DateTime");

                    b.ToTable("Transaction");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Transaction");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("GroupSplit.Data.Entities.TransactionSplit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<Guid>("TransactionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("TransactionId", "UserId")
                        .IsUnique();

                    b.ToTable("TransactionSplit");
                });

            modelBuilder.Entity("GroupSplit.Data.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("FirstName")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("LastName")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("User");
                });

            modelBuilder.Entity("GroupSplit.Data.Entities.UserIdentity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("IdentityId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("IdentityId")
                        .IsUnique();

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("UserIdentity");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.DataProtection.EntityFrameworkCore.DataProtectionKey", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("FriendlyName")
                        .HasColumnType("text");

                    b.Property<string>("Xml")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("DataProtectionKeys");
                });

            modelBuilder.Entity("GroupSplit.Data.Entities.PayerSplitRule", b =>
                {
                    b.HasBaseType("GroupSplit.Data.Entities.SplitRule");

                    b.HasDiscriminator().HasValue("PayerSplitRule");
                });

            modelBuilder.Entity("GroupSplit.Data.Entities.WeightedSplitRule", b =>
                {
                    b.HasBaseType("GroupSplit.Data.Entities.SplitRule");

                    b.HasDiscriminator().HasValue("WeightedSplitRule");
                });

            modelBuilder.Entity("GroupSplit.Data.Entities.Expense", b =>
                {
                    b.HasBaseType("GroupSplit.Data.Entities.Transaction");

                    b.Property<Guid?>("CategoryId")
                        .HasColumnType("uuid");

                    b.HasIndex("CategoryId");

                    b.HasDiscriminator().HasValue("Expense");
                });

            modelBuilder.Entity("GroupSplit.Data.Entities.Transfer", b =>
                {
                    b.HasBaseType("GroupSplit.Data.Entities.Transaction");

                    b.HasDiscriminator().HasValue("Transfer");
                });

            modelBuilder.Entity("GroupSplit.Data.Entities.EvenSplitRule", b =>
                {
                    b.HasBaseType("GroupSplit.Data.Entities.WeightedSplitRule");

                    b.HasDiscriminator().HasValue("EvenSplitRule");
                });

            modelBuilder.Entity("GroupSplit.Data.Entities.PercentSplitRule", b =>
                {
                    b.HasBaseType("GroupSplit.Data.Entities.WeightedSplitRule");

                    b.HasDiscriminator().HasValue("PercentSplitRule");
                });

            modelBuilder.Entity("GroupSplit.Data.Entities.SharesSplitRule", b =>
                {
                    b.HasBaseType("GroupSplit.Data.Entities.WeightedSplitRule");

                    b.HasDiscriminator().HasValue("SharesSplitRule");
                });

            modelBuilder.Entity("GroupSplit.Data.Entities.BankConnection", b =>
                {
                    b.HasOne("GroupSplit.Data.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("GroupSplit.Data.Entities.BankMatchDismissal", b =>
                {
                    b.HasOne("GroupSplit.Data.Entities.BankTransaction", "BankTransaction")
                        .WithMany()
                        .HasForeignKey("BankTransactionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GroupSplit.Data.Entities.Transaction", "Transaction")
                        .WithMany()
                        .HasForeignKey("TransactionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BankTransaction");

                    b.Navigation("Transaction");
                });

            modelBuilder.Entity("GroupSplit.Data.Entities.BankTransaction", b =>
                {
                    b.HasOne("GroupSplit.Data.Entities.LinkedAccount", "Account")
                        .WithMany("Transactions")
                        .HasForeignKey("LinkedAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GroupSplit.Data.Entities.Merchant", "Merchant")
                        .WithMany()
                        .HasForeignKey("MerchantId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("GroupSplit.Data.Entities.BankTransaction", "Replaces")
                        .WithMany()
                        .HasForeignKey("ReplacesId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Account");

                    b.Navigation("Merchant");

                    b.Navigation("Replaces");
                });

            modelBuilder.Entity("GroupSplit.Data.Entities.Category", b =>
                {
                    b.HasOne("GroupSplit.Data.Entities.SplitRule", "DefaultSplitRule")
                        .WithMany()
                        .HasForeignKey("DefaultSplitRuleId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("GroupSplit.Data.Entities.Group", "Group")
                        .WithMany("Categories")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DefaultSplitRule");

                    b.Navigation("Group");
                });

            modelBuilder.Entity("GroupSplit.Data.Entities.GroupInvitation", b =>
                {
                    b.HasOne("GroupSplit.Data.Entities.Group", "Group")
                        .WithMany("Invitations")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GroupSplit.Data.Entities.User", "InvitedBy")
                        .WithMany()
                        .HasForeignKey("InvitedByUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Group");

                    b.Navigation("InvitedBy");
                });

            modelBuilder.Entity("GroupSplit.Data.Entities.GroupJoinLink", b =>
                {
                    b.HasOne("GroupSplit.Data.Entities.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("GroupSplit.Data.Entities.Group", "Group")
                        .WithMany("JoinLinks")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatedBy");

                    b.Navigation("Group");
                });

            modelBuilder.Entity("GroupSplit.Data.Entities.GroupMembership", b =>
                {
                    b.HasOne("GroupSplit.Data.Entities.Group", null)
                        .WithMany()
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GroupSplit.Data.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GroupSplit.Data.Entities.LinkedAccount", b =>
                {
                    b.HasOne("GroupSplit.Data.Entities.BankConnection", "Connection")
                        .WithMany("Accounts")
                        .HasForeignKey("BankConnectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Connection");
                });

            modelBuilder.Entity("GroupSplit.Data.Entities.PendingBankLink", b =>
                {
                    b.HasOne("GroupSplit.Data.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("GroupSplit.Data.Entities.SplitRule", b =>
                {
                    b.HasOne("GroupSplit.Data.Entities.Group", "Group")
                        .WithMany("SplitRules")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");
                });

            modelBuilder.Entity("GroupSplit.Data.Entities.SplitRuleParticipant", b =>
                {
                    b.HasOne("GroupSplit.Data.Entities.WeightedSplitRule", "SplitRule")
                        .WithMany("Participants")
                        .HasForeignKey("SplitRuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GroupSplit.Data.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SplitRule");

                    b.Navigation("User");
                });

            modelBuilder.Entity("GroupSplit.Data.Entities.Transaction", b =>
                {
                    b.HasOne("GroupSplit.Data.Entities.BankTransaction", "BankTransaction")
                        .WithOne("FiledAs")
                        .HasForeignKey("GroupSplit.Data.Entities.Transaction", "BankTransactionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("GroupSplit.Data.Entities.Group", "Group")
                        .WithMany()
                        .HasForeignKey("GroupId");

                    b.HasOne("GroupSplit.Data.Entities.Merchant", "Merchant")
                        .WithMany("Transactions")
                        .HasForeignKey("MerchantId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("GroupSplit.Data.Entities.User", "User")
                        .WithMany("Transactions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BankTransaction");

                    b.Navigation("Group");

                    b.Navigation("Merchant");

                    b.Navigation("User");
                });

            modelBuilder.Entity("GroupSplit.Data.Entities.TransactionSplit", b =>
                {
                    b.HasOne("GroupSplit.Data.Entities.Transaction", "Transaction")
                        .WithMany("Splits")
                        .HasForeignKey("TransactionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GroupSplit.Data.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Transaction");

                    b.Navigation("User");
                });

            modelBuilder.Entity("GroupSplit.Data.Entities.UserIdentity", b =>
                {
                    b.HasOne("GroupSplit.Data.Entities.User", "User")
                        .WithOne("Identity")
                        .HasForeignKey("GroupSplit.Data.Entities.UserIdentity", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("GroupSplit.Data.Entities.Expense", b =>
                {
                    b.HasOne("GroupSplit.Data.Entities.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Category");
                });

            modelBuilder.Entity("GroupSplit.Data.Entities.BankConnection", b =>
                {
                    b.Navigation("Accounts");
                });

            modelBuilder.Entity("GroupSplit.Data.Entities.BankTransaction", b =>
                {
                    b.Navigation("FiledAs");
                });

            modelBuilder.Entity("GroupSplit.Data.Entities.Group", b =>
                {
                    b.Navigation("Categories");

                    b.Navigation("Invitations");

                    b.Navigation("JoinLinks");

                    b.Navigation("SplitRules");
                });

            modelBuilder.Entity("GroupSplit.Data.Entities.LinkedAccount", b =>
                {
                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("GroupSplit.Data.Entities.Merchant", b =>
                {
                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("GroupSplit.Data.Entities.Transaction", b =>
                {
                    b.Navigation("Splits");
                });

            modelBuilder.Entity("GroupSplit.Data.Entities.User", b =>
                {
                    b.Navigation("Identity")
                        .IsRequired();

                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("GroupSplit.Data.Entities.WeightedSplitRule", b =>
                {
                    b.Navigation("Participants");
                });
#pragma warning restore 612, 618
        }
    }
}
