// <auto-generated />
using System;
using GroupSplit.Data.PostgreSQL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GroupSplit.Data.PostgreSQL.Migrations.Migrations
{
    [DbContext(typeof(PostgreSqlAppDbContext))]
    partial class PostgreSqlAppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GroupSplit.Data.Entities.Group", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.ToTable("Group");
                });

            modelBuilder.Entity("GroupSplit.Data.Entities.PercentRuleUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double>("Percentage")
                        .HasColumnType("double precision");

                    b.Property<Guid>("RuleVersionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RuleVersionId");

                    b.HasIndex("UserId", "RuleVersionId")
                        .IsUnique();

                    b.ToTable("PercentRuleUser");
                });

            modelBuilder.Entity("GroupSplit.Data.Entities.Rule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int>("Flags")
                        .HasColumnType("integer");

                    b.Property<Guid>("GroupId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Category");

                    b.HasIndex("GroupId", "Category")
                        .IsUnique();

                    b.ToTable("Rule");
                });

            modelBuilder.Entity("GroupSplit.Data.Entities.RuleVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("EndDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("RuleId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("StartDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("RuleId");

                    b.ToTable("RuleVersion");

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("GroupSplit.Data.Entities.SharesRuleUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("RuleVersionId")
                        .HasColumnType("uuid");

                    b.Property<int>("Shares")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RuleVersionId");

                    b.HasIndex("UserId", "RuleVersionId")
                        .IsUnique();

                    b.ToTable("SharesRuleUser");
                });

            modelBuilder.Entity("GroupSplit.Data.Entities.Transaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTimeOffset>("DateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<Guid>("RuleVersionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("DateTime");

                    b.HasIndex("Name");

                    b.HasIndex("RuleVersionId");

                    b.HasIndex("UserId");

                    b.ToTable("Transaction");
                });

            modelBuilder.Entity("GroupSplit.Data.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("FirstName")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("LastName")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid>("PersonalGroupId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("PersonalGroupId")
                        .IsUnique();

                    b.ToTable("User");
                });

            modelBuilder.Entity("GroupSplit.Data.Entities.UserIdentity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("IdentityId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("IdentityId")
                        .IsUnique();

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("UserIdentity");
                });

            modelBuilder.Entity("GroupUser", b =>
                {
                    b.Property<Guid>("GroupsId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UsersId")
                        .HasColumnType("uuid");

                    b.HasKey("GroupsId", "UsersId");

                    b.HasIndex("UsersId");

                    b.ToTable("GroupUser");
                });

            modelBuilder.Entity("GroupSplit.Data.Entities.PercentRuleVersion", b =>
                {
                    b.HasBaseType("GroupSplit.Data.Entities.RuleVersion");

                    b.ToTable("PercentRuleVersion");
                });

            modelBuilder.Entity("GroupSplit.Data.Entities.PersonalRuleVersion", b =>
                {
                    b.HasBaseType("GroupSplit.Data.Entities.RuleVersion");

                    b.ToTable("PersonalRuleVersion");
                });

            modelBuilder.Entity("GroupSplit.Data.Entities.SettlementRuleVersion", b =>
                {
                    b.HasBaseType("GroupSplit.Data.Entities.RuleVersion");

                    b.Property<Guid>("OtherUserId")
                        .HasColumnType("uuid");

                    b.HasIndex("OtherUserId");

                    b.ToTable("SettlementRuleVersion");
                });

            modelBuilder.Entity("GroupSplit.Data.Entities.SharesRuleVersion", b =>
                {
                    b.HasBaseType("GroupSplit.Data.Entities.PercentRuleVersion");

                    b.ToTable("SharesRuleVersion");
                });

            modelBuilder.Entity("GroupSplit.Data.Entities.PercentRuleUser", b =>
                {
                    b.HasOne("GroupSplit.Data.Entities.PercentRuleVersion", "RuleVersion")
                        .WithMany("RuleUsers")
                        .HasForeignKey("RuleVersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GroupSplit.Data.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RuleVersion");

                    b.Navigation("User");
                });

            modelBuilder.Entity("GroupSplit.Data.Entities.Rule", b =>
                {
                    b.HasOne("GroupSplit.Data.Entities.Group", "Group")
                        .WithMany("Rules")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");
                });

            modelBuilder.Entity("GroupSplit.Data.Entities.RuleVersion", b =>
                {
                    b.HasOne("GroupSplit.Data.Entities.Rule", "Rule")
                        .WithMany("Versions")
                        .HasForeignKey("RuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rule");
                });

            modelBuilder.Entity("GroupSplit.Data.Entities.SharesRuleUser", b =>
                {
                    b.HasOne("GroupSplit.Data.Entities.SharesRuleVersion", "RuleVersion")
                        .WithMany("SharedRuleUsers")
                        .HasForeignKey("RuleVersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GroupSplit.Data.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RuleVersion");

                    b.Navigation("User");
                });

            modelBuilder.Entity("GroupSplit.Data.Entities.Transaction", b =>
                {
                    b.HasOne("GroupSplit.Data.Entities.RuleVersion", "RuleVersion")
                        .WithMany("Transactions")
                        .HasForeignKey("RuleVersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GroupSplit.Data.Entities.User", "User")
                        .WithMany("Transactions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RuleVersion");

                    b.Navigation("User");
                });

            modelBuilder.Entity("GroupSplit.Data.Entities.User", b =>
                {
                    b.HasOne("GroupSplit.Data.Entities.Group", "PersonalGroup")
                        .WithOne()
                        .HasForeignKey("GroupSplit.Data.Entities.User", "PersonalGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PersonalGroup");
                });

            modelBuilder.Entity("GroupSplit.Data.Entities.UserIdentity", b =>
                {
                    b.HasOne("GroupSplit.Data.Entities.User", "User")
                        .WithOne("Identity")
                        .HasForeignKey("GroupSplit.Data.Entities.UserIdentity", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("GroupUser", b =>
                {
                    b.HasOne("GroupSplit.Data.Entities.Group", null)
                        .WithMany()
                        .HasForeignKey("GroupsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GroupSplit.Data.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UsersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GroupSplit.Data.Entities.PercentRuleVersion", b =>
                {
                    b.HasOne("GroupSplit.Data.Entities.RuleVersion", null)
                        .WithOne()
                        .HasForeignKey("GroupSplit.Data.Entities.PercentRuleVersion", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GroupSplit.Data.Entities.PersonalRuleVersion", b =>
                {
                    b.HasOne("GroupSplit.Data.Entities.RuleVersion", null)
                        .WithOne()
                        .HasForeignKey("GroupSplit.Data.Entities.PersonalRuleVersion", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GroupSplit.Data.Entities.SettlementRuleVersion", b =>
                {
                    b.HasOne("GroupSplit.Data.Entities.RuleVersion", null)
                        .WithOne()
                        .HasForeignKey("GroupSplit.Data.Entities.SettlementRuleVersion", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GroupSplit.Data.Entities.User", "OtherUser")
                        .WithMany()
                        .HasForeignKey("OtherUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OtherUser");
                });

            modelBuilder.Entity("GroupSplit.Data.Entities.SharesRuleVersion", b =>
                {
                    b.HasOne("GroupSplit.Data.Entities.PercentRuleVersion", null)
                        .WithOne()
                        .HasForeignKey("GroupSplit.Data.Entities.SharesRuleVersion", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GroupSplit.Data.Entities.Group", b =>
                {
                    b.Navigation("Rules");
                });

            modelBuilder.Entity("GroupSplit.Data.Entities.Rule", b =>
                {
                    b.Navigation("Versions");
                });

            modelBuilder.Entity("GroupSplit.Data.Entities.RuleVersion", b =>
                {
                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("GroupSplit.Data.Entities.User", b =>
                {
                    b.Navigation("Identity")
                        .IsRequired();

                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("GroupSplit.Data.Entities.PercentRuleVersion", b =>
                {
                    b.Navigation("RuleUsers");
                });

            modelBuilder.Entity("GroupSplit.Data.Entities.SharesRuleVersion", b =>
                {
                    b.Navigation("SharedRuleUsers");
                });
#pragma warning restore 612, 618
        }
    }
}
