// <auto-generated />
using System;
using GroupSplit.Data.PostgreSQL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GroupSplit.Data.PostgreSQL.Migrations.Migrations
{
    [DbContext(typeof(PostgreSqlAppDbContext))]
    partial class PostgreSqlAppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GroupSplit.Data.Entities.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("DefaultSplitRuleId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("GroupId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.HasIndex("DefaultSplitRuleId");

                    b.HasIndex("GroupId", "Name")
                        .IsUnique();

                    b.ToTable("Category");
                });

            modelBuilder.Entity("GroupSplit.Data.Entities.Group", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(3)
                        .HasColumnType("character(3)")
                        .HasDefaultValue("USD")
                        .IsFixedLength();

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.ToTable("Group");
                });

            modelBuilder.Entity("GroupSplit.Data.Entities.GroupInvitation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<Guid>("GroupId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("InvitedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("InvitedByUserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Email");

                    b.HasIndex("InvitedByUserId");

                    b.HasIndex("GroupId", "Email")
                        .IsUnique();

                    b.ToTable("GroupInvitation");
                });

            modelBuilder.Entity("GroupSplit.Data.Entities.GroupMembership", b =>
                {
                    b.Property<Guid>("GroupId")
                        .HasColumnType("uuid")
                        .HasColumnName("GroupsId");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("UsersId");

                    b.Property<DateTimeOffset?>("ArchivedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("JoinedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("GroupId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("GroupUser", (string)null);
                });

            modelBuilder.Entity("GroupSplit.Data.Entities.SplitRule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("character varying(21)");

                    b.Property<Guid>("GroupId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.HasIndex("Discriminator");

                    b.HasIndex("GroupId", "Name")
                        .IsUnique();

                    b.ToTable("SplitRule");

                    b.HasDiscriminator<string>("Discriminator").HasValue("SplitRule");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("GroupSplit.Data.Entities.SplitRuleParticipant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("SplitRuleId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<int>("Weight")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("SplitRuleId", "UserId")
                        .IsUnique();

                    b.ToTable("SplitRuleParticipant");
                });

            modelBuilder.Entity("GroupSplit.Data.Entities.Transaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(3)
                        .HasColumnType("character(3)")
                        .HasDefaultValue("USD")
                        .IsFixedLength();

                    b.Property<DateTimeOffset>("DateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("character varying(13)");

                    b.Property<Guid?>("GroupId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("DateTime");

                    b.HasIndex("Discriminator");

                    b.HasIndex("Name");

                    b.HasIndex("UserId");

                    b.HasIndex("GroupId", "DateTime");

                    b.ToTable("Transaction");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Transaction");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("GroupSplit.Data.Entities.TransactionSplit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<Guid>("TransactionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("TransactionId", "UserId")
                        .IsUnique();

                    b.ToTable("TransactionSplit");
                });

            modelBuilder.Entity("GroupSplit.Data.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("FirstName")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("LastName")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("User");
                });

            modelBuilder.Entity("GroupSplit.Data.Entities.UserIdentity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("IdentityId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("IdentityId")
                        .IsUnique();

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("UserIdentity");
                });

            modelBuilder.Entity("GroupSplit.Data.Entities.PayerSplitRule", b =>
                {
                    b.HasBaseType("GroupSplit.Data.Entities.SplitRule");

                    b.HasDiscriminator().HasValue("PayerSplitRule");
                });

            modelBuilder.Entity("GroupSplit.Data.Entities.WeightedSplitRule", b =>
                {
                    b.HasBaseType("GroupSplit.Data.Entities.SplitRule");

                    b.HasDiscriminator().HasValue("WeightedSplitRule");
                });

            modelBuilder.Entity("GroupSplit.Data.Entities.Expense", b =>
                {
                    b.HasBaseType("GroupSplit.Data.Entities.Transaction");

                    b.Property<Guid?>("CategoryId")
                        .HasColumnType("uuid");

                    b.HasIndex("CategoryId");

                    b.HasDiscriminator().HasValue("Expense");
                });

            modelBuilder.Entity("GroupSplit.Data.Entities.Transfer", b =>
                {
                    b.HasBaseType("GroupSplit.Data.Entities.Transaction");

                    b.HasDiscriminator().HasValue("Transfer");
                });

            modelBuilder.Entity("GroupSplit.Data.Entities.EvenSplitRule", b =>
                {
                    b.HasBaseType("GroupSplit.Data.Entities.WeightedSplitRule");

                    b.HasDiscriminator().HasValue("EvenSplitRule");
                });

            modelBuilder.Entity("GroupSplit.Data.Entities.PercentSplitRule", b =>
                {
                    b.HasBaseType("GroupSplit.Data.Entities.WeightedSplitRule");

                    b.HasDiscriminator().HasValue("PercentSplitRule");
                });

            modelBuilder.Entity("GroupSplit.Data.Entities.SharesSplitRule", b =>
                {
                    b.HasBaseType("GroupSplit.Data.Entities.WeightedSplitRule");

                    b.HasDiscriminator().HasValue("SharesSplitRule");
                });

            modelBuilder.Entity("GroupSplit.Data.Entities.Category", b =>
                {
                    b.HasOne("GroupSplit.Data.Entities.SplitRule", "DefaultSplitRule")
                        .WithMany()
                        .HasForeignKey("DefaultSplitRuleId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("GroupSplit.Data.Entities.Group", "Group")
                        .WithMany("Categories")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DefaultSplitRule");

                    b.Navigation("Group");
                });

            modelBuilder.Entity("GroupSplit.Data.Entities.GroupInvitation", b =>
                {
                    b.HasOne("GroupSplit.Data.Entities.Group", "Group")
                        .WithMany("Invitations")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GroupSplit.Data.Entities.User", "InvitedBy")
                        .WithMany()
                        .HasForeignKey("InvitedByUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Group");

                    b.Navigation("InvitedBy");
                });

            modelBuilder.Entity("GroupSplit.Data.Entities.GroupMembership", b =>
                {
                    b.HasOne("GroupSplit.Data.Entities.Group", null)
                        .WithMany()
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GroupSplit.Data.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GroupSplit.Data.Entities.SplitRule", b =>
                {
                    b.HasOne("GroupSplit.Data.Entities.Group", "Group")
                        .WithMany("SplitRules")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");
                });

            modelBuilder.Entity("GroupSplit.Data.Entities.SplitRuleParticipant", b =>
                {
                    b.HasOne("GroupSplit.Data.Entities.WeightedSplitRule", "SplitRule")
                        .WithMany("Participants")
                        .HasForeignKey("SplitRuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GroupSplit.Data.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SplitRule");

                    b.Navigation("User");
                });

            modelBuilder.Entity("GroupSplit.Data.Entities.Transaction", b =>
                {
                    b.HasOne("GroupSplit.Data.Entities.Group", "Group")
                        .WithMany()
                        .HasForeignKey("GroupId");

                    b.HasOne("GroupSplit.Data.Entities.User", "User")
                        .WithMany("Transactions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");

                    b.Navigation("User");
                });

            modelBuilder.Entity("GroupSplit.Data.Entities.TransactionSplit", b =>
                {
                    b.HasOne("GroupSplit.Data.Entities.Transaction", "Transaction")
                        .WithMany("Splits")
                        .HasForeignKey("TransactionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GroupSplit.Data.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Transaction");

                    b.Navigation("User");
                });

            modelBuilder.Entity("GroupSplit.Data.Entities.UserIdentity", b =>
                {
                    b.HasOne("GroupSplit.Data.Entities.User", "User")
                        .WithOne("Identity")
                        .HasForeignKey("GroupSplit.Data.Entities.UserIdentity", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("GroupSplit.Data.Entities.Expense", b =>
                {
                    b.HasOne("GroupSplit.Data.Entities.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Category");
                });

            modelBuilder.Entity("GroupSplit.Data.Entities.Group", b =>
                {
                    b.Navigation("Categories");

                    b.Navigation("Invitations");

                    b.Navigation("SplitRules");
                });

            modelBuilder.Entity("GroupSplit.Data.Entities.Transaction", b =>
                {
                    b.Navigation("Splits");
                });

            modelBuilder.Entity("GroupSplit.Data.Entities.User", b =>
                {
                    b.Navigation("Identity")
                        .IsRequired();

                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("GroupSplit.Data.Entities.WeightedSplitRule", b =>
                {
                    b.Navigation("Participants");
                });
#pragma warning restore 612, 618
        }
    }
}
