<Project Sdk="Aspire.AppHost.Sdk/13.0.0">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <UserSecretsId>031551fd-13d2-4a55-a125-47bb17c6ec44</UserSecretsId>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\GroupSplit.API\GroupSplit.API.csproj" />
      <ProjectReference Include="..\GroupSplit.Data.Migrations.PostgreSQL\GroupSplit.Data.Migrations.PostgreSQL.csproj"/>
      <ProjectReference Include="..\GroupSplit.Identity.Migrations.PostgreSQL\GroupSplit.Identity.Migrations.PostgreSQL.csproj" />
      <ProjectReference Include="..\GroupSplit.Web\GroupSplit.Web.csproj"  />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Aspire.Hosting.PostgreSQL" Version="13.0.0" />
    </ItemGroup>

</Project>
