namespace GroupSplit.Data.Entities;

/// <summary>
/// One member paying another back.
/// </summary>
/// <remarks>
/// A settlement used to be two rows -- <c>+amount</c> against the other member and
/// <c>-amount</c> against you -- hung off a pseudo-rule that existed to be excluded from
/// things, carrying flags that existed to stop anybody recording against it. A transfer is
/// one row that goes through the same splits, the same balance query and the same delete
/// path as everything else, and needs no flags because there is nothing to forbid.
/// <para>
/// Members had already invented this: the Home group worked around the Settle button by
/// making a "Daniel pays" rule with one participant at 100% and recording repayments as
/// ordinary expenses against it. The arithmetic was right; only the modelling was missing.
/// </para>
/// </remarks>
public class Transfer : Transaction
{
    /// <summary>
    /// The settling-up that generated this payment, or null for one somebody recorded by
    /// hand.
    /// </summary>
    /// <remarks>
    /// Not the same question as <see cref="Transaction.SettlementRun"/>, which says what
    /// swept it. A run sweeps the transfers it writes and also any earlier repayment in its
    /// reach, and those two both end up pointing at the run -- so without this, a run asked
    /// what it paid would count somebody's hand-recorded 30 as its own.
    /// <para>
    /// It survives a reopening, where the sweep marker does not: the payment was still
    /// generated by that run, whatever became of the claim the run was making.
    /// </para>
    /// </remarks>
    public virtual SettlementRun? WrittenByRun { get; set; }

    public Guid? WrittenByRunId { get; set; }

    /// <summary>
    /// For EF, and to keep <see cref="Between"/> the only way anybody else can make one.
    /// </summary>
    private Transfer()
    {
    }

    /// <summary>
    /// Money moving from one member to another, as a single row with a single split.
    /// </summary>
    /// <remarks>
    /// The one split -- to the recipient, for the whole amount -- is what makes the
    /// balances come out right: the payer's <c>paid</c> rises by the amount and the
    /// recipient's <c>owed</c> rises by it, so the payer's net goes up and the
    /// recipient's goes down, which is exactly what paying somebody back means. It is
    /// also the invariant that has no second chance, so nothing outside this type is
    /// allowed to construct a transfer and forget it.
    /// </remarks>
    /// <param name="description">
    /// What the payer wants remembered about it -- "cash", "bank transfer, ref 4821" -- or
    /// the name of the settling-up that generated it. The column was always here and
    /// nothing ever set it, so a group's activity could say that Loraine paid Daniel 40 and
    /// never how.
    /// </param>
    public static Transfer Between(Group group, User from, User to, decimal amount, DateTimeOffset date,
        string? description = null)
    {
        ArgumentNullException.ThrowIfNull(group);
        ArgumentNullException.ThrowIfNull(from);
        ArgumentNullException.ThrowIfNull(to);

        if (from == to)
            throw new ArgumentException("A transfer needs two different people.", nameof(to));

        var transfer = new Transfer
        {
            Group = group,
            Amount = amount,
            Currency = group.Currency,
            DateTime = date,
            Name = "Settlement",
            Description = description,
            User = from
        };

        transfer.Splits.Add(new TransactionSplit { User = to, Amount = amount });

        return transfer;
    }
}
