<Project Sdk="Microsoft.NET.Sdk.Razor">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <ApiProject>..\..\GroupSplit.API\GroupSplit.API.csproj</ApiProject>
    </PropertyGroup>

    <ItemGroup>
        <SupportedPlatform Include="browser"/>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.AspNetCore.Components.Authorization" Version="10.0.11" />
        <PackageReference Include="Microsoft.AspNetCore.Components.Web" Version="10.0.11" />
        <PackageReference Include="Microsoft.AspNetCore.JsonPatch.SystemTextJson" Version="10.0.11" />
        <PackageReference Include="Microsoft.Extensions.Http" Version="10.0.11" />
        <PackageReference Include="MudBlazor" Version="9.9.0" />
        <PackageReference Include="NSwag.ApiDescription.Client" Version="14.7.1">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\GroupSplit.API\GroupSplit.API.csproj"
                          ReferenceOutputAssembly="false"
                          PrivateAssets="all"/>
        <ProjectReference Include="..\..\GroupSplit.Shared\GroupSplit.Shared.csproj"/>
    </ItemGroup>
    
    <ItemGroup>
        <OpenApiReference Include="..\..\GroupSplit.API\obj\Generated\GroupSplit.API_api.json">
            <ClassName>{controller}Client</ClassName>
            <Namespace>GroupSplit.Shared</Namespace>
            <Options>/TemplateDirectory:.\ClientTemplates /GenerateClientInterfaces:true /GenerateDtoTypes:false /UseBaseUrl:false /QueryNullValue:null /OperationGenerationMode:MultipleClientsFromFirstTagAndOperationId /GenerateOptionalParameters:true /DateType:DateOnly /TimeType:TimeOnly /DateTimeType:DateTimeOffset /JsonLibrary:SystemTextJson /JsonSerializerSettingsTransformationMethod:GroupSplitSerializer.Transform</Options>
        </OpenApiReference>
    </ItemGroup>

</Project>