<Project Sdk="Microsoft.NET.Sdk.Razor">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <ApiProject>..\..\GroupSplit.API\GroupSplit.API.csproj</ApiProject>
    </PropertyGroup>

    <ItemGroup>
        <SupportedPlatform Include="browser" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.AspNetCore.Components.Authorization" Version="10.0.0" />
        <PackageReference Include="Microsoft.AspNetCore.Components.Web" Version="10.0.0" />
        <PackageReference Include="Microsoft.AspNetCore.Identity" Version="2.2.0" />
        <PackageReference Include="Microsoft.Extensions.Http" Version="10.0.0" />
        <PackageReference Include="MudBlazor" Version="8.14.0" />
        <PackageReference Include="NSwag.MSBuild" Version="14.6.2">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\GroupSplit.Shared\GroupSplit.Shared.csproj" />
    </ItemGroup>

    <ItemGroup>
        <Compile Include="obj\Generated\**\*.cs">
            <Visible>false</Visible>
        </Compile>
    </ItemGroup>

    <Target Name="NSwag" BeforeTargets="CoreCompile" Condition=" '$(Configuration)' == 'Debug' ">
        <Exec WorkingDirectory="$(ProjectDir)" EnvironmentVariables="ASPNETCORE_ENVIRONMENT=Development" Command="$(NSwagExe_Net100) run nswag.json /variables:Configuration=$(Configuration),Project=$(ApiProject)" />
        <Exec WorkingDirectory="$(ProjectDir)" EnvironmentVariables="ASPNETCORE_ENVIRONMENT=Development" Command="$(NSwagExe_Net100) run identity.nswag.json /variables:Configuration=$(Configuration),Project=$(ApiProject)" />
    </Target>

</Project>