// <auto-generated />
using System;
using GroupSplit.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GroupSplit.Data.Migrations.PostgreSQL.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251120043057_AddPersonalGroup")]
    partial class AddPersonalGroup
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0-rc.2.25502.107")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GroupSplit.Data.Entities.Group", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("Group");
                });

            modelBuilder.Entity("GroupSplit.Data.Entities.PercentRuleUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double>("Percentage")
                        .HasColumnType("double precision");

                    b.Property<Guid>("RuleVersionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RuleVersionId");

                    b.HasIndex("UserId", "RuleVersionId")
                        .IsUnique();

                    b.ToTable("PercentRuleUser");
                });

            modelBuilder.Entity("GroupSplit.Data.Entities.Rule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid>("GroupId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("GroupId");

                    b.ToTable("Rule");
                });

            modelBuilder.Entity("GroupSplit.Data.Entities.RuleVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("RuleId")
                        .HasColumnType("uuid");

                    b.Property<string>("RuleType")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("character varying(13)");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("RuleId");

                    b.ToTable("RuleVersion");

                    b.HasDiscriminator<string>("RuleType").HasValue("RuleVersion");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("GroupSplit.Data.Entities.Transaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<Guid>("GroupId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("GroupId");

                    b.HasIndex("UserId");

                    b.ToTable("Transaction");
                });

            modelBuilder.Entity("GroupSplit.Data.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("PersonalGroupId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PersonalGroupId")
                        .IsUnique();

                    b.ToTable("User");
                });

            modelBuilder.Entity("GroupSplit.Data.Entities.UserIdentity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("IdentityId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("IdentityId")
                        .IsUnique();

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("UserIdentity");
                });

            modelBuilder.Entity("GroupUser", b =>
                {
                    b.Property<Guid>("GroupsId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UsersId")
                        .HasColumnType("uuid");

                    b.HasKey("GroupsId", "UsersId");

                    b.HasIndex("UsersId");

                    b.ToTable("GroupUser");
                });

            modelBuilder.Entity("GroupSplit.Data.Entities.PercentRuleVersion", b =>
                {
                    b.HasBaseType("GroupSplit.Data.Entities.RuleVersion");

                    b.HasDiscriminator().HasValue("percent");
                });

            modelBuilder.Entity("GroupSplit.Data.Entities.PersonalRuleVersion", b =>
                {
                    b.HasBaseType("GroupSplit.Data.Entities.RuleVersion");

                    b.HasDiscriminator().HasValue("personal");
                });

            modelBuilder.Entity("GroupSplit.Data.Entities.PercentRuleUser", b =>
                {
                    b.HasOne("GroupSplit.Data.Entities.PercentRuleVersion", "RuleVersion")
                        .WithMany("RuleUsers")
                        .HasForeignKey("RuleVersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GroupSplit.Data.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RuleVersion");

                    b.Navigation("User");
                });

            modelBuilder.Entity("GroupSplit.Data.Entities.Rule", b =>
                {
                    b.HasOne("GroupSplit.Data.Entities.Group", "Group")
                        .WithMany("Rules")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");
                });

            modelBuilder.Entity("GroupSplit.Data.Entities.RuleVersion", b =>
                {
                    b.HasOne("GroupSplit.Data.Entities.Rule", "Rule")
                        .WithMany("Versions")
                        .HasForeignKey("RuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rule");
                });

            modelBuilder.Entity("GroupSplit.Data.Entities.Transaction", b =>
                {
                    b.HasOne("GroupSplit.Data.Entities.Group", "Group")
                        .WithMany("Transactions")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GroupSplit.Data.Entities.User", "User")
                        .WithMany("Transactions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");

                    b.Navigation("User");
                });

            modelBuilder.Entity("GroupSplit.Data.Entities.User", b =>
                {
                    b.HasOne("GroupSplit.Data.Entities.Group", "PersonalGroup")
                        .WithOne()
                        .HasForeignKey("GroupSplit.Data.Entities.User", "PersonalGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PersonalGroup");
                });

            modelBuilder.Entity("GroupSplit.Data.Entities.UserIdentity", b =>
                {
                    b.HasOne("GroupSplit.Data.Entities.User", "User")
                        .WithOne("Identity")
                        .HasForeignKey("GroupSplit.Data.Entities.UserIdentity", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("GroupUser", b =>
                {
                    b.HasOne("GroupSplit.Data.Entities.Group", null)
                        .WithMany()
                        .HasForeignKey("GroupsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GroupSplit.Data.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UsersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GroupSplit.Data.Entities.Group", b =>
                {
                    b.Navigation("Rules");

                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("GroupSplit.Data.Entities.Rule", b =>
                {
                    b.Navigation("Versions");
                });

            modelBuilder.Entity("GroupSplit.Data.Entities.User", b =>
                {
                    b.Navigation("Identity")
                        .IsRequired();

                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("GroupSplit.Data.Entities.PercentRuleVersion", b =>
                {
                    b.Navigation("RuleUsers");
                });
#pragma warning restore 612, 618
        }
    }
}
